//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: reef_protocol.proto
// Note: requires additional types generated from: client_runtime.proto
// Note: requires additional types generated from: evaluator_runtime.proto
// Note: requires additional types generated from: reef_service_protos.proto
using Org.Apache.Reef.Common.ProtoBuf.ClienRuntimeProto;
using Org.Apache.Reef.Common.ProtoBuf.EvaluatorRunTimeProto;
using Org.Apache.Reef.Common.ProtoBuf.ReefServiceProto;

namespace Org.Apache.Reef.Common.ProtoBuf.ReefProtocol
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"REEFMessage")]
  public partial class REEFMessage : global::ProtoBuf.IExtensible
  {
    public REEFMessage() {}
    
    private JobSubmissionProto _jobSubmission = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"jobSubmission", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public JobSubmissionProto jobSubmission
    {
      get { return _jobSubmission; }
      set { _jobSubmission = value; }
    }
    private JobControlProto _jobControl = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"jobControl", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public JobControlProto jobControl
    {
      get { return _jobControl; }
      set { _jobControl = value; }
    }
    private RuntimeErrorProto _runtimeError = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"runtimeError", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public RuntimeErrorProto runtimeError
    {
      get { return _runtimeError; }
      set { _runtimeError = value; }
    }
    private JobStatusProto _jobStatus = null;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"jobStatus", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public JobStatusProto jobStatus
    {
      get { return _jobStatus; }
      set { _jobStatus = value; }
    }
    private EvaluatorControlProto _evaluatorControl = null;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"evaluatorControl", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public EvaluatorControlProto evaluatorControl
    {
      get { return _evaluatorControl; }
      set { _evaluatorControl = value; }
    }
    private EvaluatorHeartbeatProto _evaluatorHeartBeat = null;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"evaluatorHeartBeat", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public EvaluatorHeartbeatProto evaluatorHeartBeat
    {
      get { return _evaluatorHeartBeat; }
      set { _evaluatorHeartBeat = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}