//<auto-generated />
namespace Org.Apache.Reef.Common.Avro
{
    using System.Runtime.Serialization;

    /// <summary>
    /// Used to serialize and deserialize Avro record org.apache.reef.webserver.AvroHttpRequest.
    /// </summary>
    [DataContract(Namespace = "org.apache.reef.webserver")]
    public partial class AvroHttpRequest
    {
        private const string JsonSchema = @"{""type"":""record"",""name"":""org.apache.reef.webserver.AvroHttpRequest"",""fields"":[{""name"":""requestUrl"",""type"":""string""},{""name"":""pathInfo"",""type"":""string""},{""name"":""queryString"",""type"":""string""},{""name"":""httpMethod"",""type"":""string""},{""name"":""inputStream"",""type"":""bytes""}]}";

        /// <summary>
        /// Gets the schema.
        /// </summary>
        public static string Schema
        {
            get
            {
                return JsonSchema;
            }
        }

        /// <summary>
        /// Gets or sets the requestUrl field.
        /// </summary>
        [DataMember]
        public string RequestUrl { get; set; }

        /// <summary>
        /// Gets or sets the pathInfo field.
        /// </summary>
        [DataMember]
        public string PathInfo { get; set; }

        /// <summary>
        /// Gets or sets the queryString field.
        /// </summary>
        [DataMember]
        public string QueryString { get; set; }

        /// <summary>
        /// Gets or sets the httpMethod field.
        /// </summary>
        [DataMember]
        public string HttpMethod { get; set; }

        /// <summary>
        /// Gets or sets the inputStream field.
        /// </summary>
        [DataMember]
        public byte[] InputStream { get; set; }

        /// <summary>
        /// Initializes a new instance of the <see cref="AvroHttpRequest"/> class.
        /// </summary>
        public AvroHttpRequest()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="AvroHttpRequest"/> class.
        /// </summary>
        /// <param name="requestUrl">The requestUrl.</param>
        /// <param name="pathInfo">The pathInfo.</param>
        /// <param name="queryString">The queryString.</param>
        /// <param name="httpMethod">The httpMethod.</param>
        /// <param name="inputStream">The inputStream.</param>
        public AvroHttpRequest(string requestUrl, string pathInfo, string queryString, string httpMethod, byte[] inputStream)
        {
            RequestUrl = requestUrl;
            PathInfo = pathInfo;
            QueryString = queryString;
            HttpMethod = httpMethod;
            InputStream = inputStream;
        }
    }
}