//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: evaluator_runtime.proto
// Note: requires additional types generated from: reef_service_protos.proto
namespace Org.Apache.REEF.Common.Protobuf.ReefProtocol
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"DoneEvaluatorProto")]
  public partial class DoneEvaluatorProto : global::ProtoBuf.IExtensible
  {
      public DoneEvaluatorProto() { }
  
      private global::ProtoBuf.IExtension extensionObject;
      global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"StopEvaluatorProto")]
  public partial class StopEvaluatorProto : global::ProtoBuf.IExtensible
  {
    public StopEvaluatorProto() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"KillEvaluatorProto")]
  public partial class KillEvaluatorProto : global::ProtoBuf.IExtensible
  {
    public KillEvaluatorProto() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"StartTaskProto")]
  public partial class StartTaskProto : global::ProtoBuf.IExtensible
  {
    public StartTaskProto() {}
    
    private string _context_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"context_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string context_id
    {
      get { return _context_id; }
      set { _context_id = value; }
    }
    private string _configuration;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"configuration", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string configuration
    {
      get { return _configuration; }
      set { _configuration = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"AddContextProto")]
  public partial class AddContextProto : global::ProtoBuf.IExtensible
  {
    public AddContextProto() {}
    
    private string _parent_context_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"parent_context_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string parent_context_id
    {
      get { return _parent_context_id; }
      set { _parent_context_id = value; }
    }
    private string _context_configuration;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"context_configuration", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string context_configuration
    {
      get { return _context_configuration; }
      set { _context_configuration = value; }
    }
    private string _service_configuration = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"service_configuration", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string service_configuration
    {
      get { return _service_configuration; }
      set { _service_configuration = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RemoveContextProto")]
  public partial class RemoveContextProto : global::ProtoBuf.IExtensible
  {
    public RemoveContextProto() {}
    
    private string _context_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"context_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string context_id
    {
      get { return _context_id; }
      set { _context_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"StopTaskProto")]
  public partial class StopTaskProto : global::ProtoBuf.IExtensible
  {
    public StopTaskProto() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SuspendTaskProto")]
  public partial class SuspendTaskProto : global::ProtoBuf.IExtensible
  {
    public SuspendTaskProto() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ContextMessageProto")]
  public partial class ContextMessageProto : global::ProtoBuf.IExtensible
  {
    public ContextMessageProto() {}
    
    private string _context_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"context_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string context_id
    {
      get { return _context_id; }
      set { _context_id = value; }
    }
    private byte[] _message;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"message", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public byte[] message
    {
      get { return _message; }
      set { _message = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ContextControlProto")]
  public partial class ContextControlProto : global::ProtoBuf.IExtensible
  {
    public ContextControlProto() {}
    
    private byte[] _task_message = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"task_message", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public byte[] task_message
    {
      get { return _task_message; }
      set { _task_message = value; }
    }
    private ContextMessageProto _context_message = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"context_message", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ContextMessageProto context_message
    {
      get { return _context_message; }
      set { _context_message = value; }
    }
    private AddContextProto _add_context = null;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"add_context", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public AddContextProto add_context
    {
      get { return _add_context; }
      set { _add_context = value; }
    }
    private RemoveContextProto _remove_context = null;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"remove_context", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public RemoveContextProto remove_context
    {
      get { return _remove_context; }
      set { _remove_context = value; }
    }
    private StartTaskProto _start_task = null;
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"start_task", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public StartTaskProto start_task
    {
      get { return _start_task; }
      set { _start_task = value; }
    }
    private StopTaskProto _stop_task = null;
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"stop_task", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public StopTaskProto stop_task
    {
      get { return _stop_task; }
      set { _stop_task = value; }
    }
    private SuspendTaskProto _suspend_task = null;
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"suspend_task", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public SuspendTaskProto suspend_task
    {
      get { return _suspend_task; }
      set { _suspend_task = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"EvaluatorHeartbeatProto")]
  public partial class EvaluatorHeartbeatProto : global::ProtoBuf.IExtensible
  {
    public EvaluatorHeartbeatProto() {}
    
    private long _timestamp;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"timestamp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long timestamp
    {
      get { return _timestamp; }
      set { _timestamp = value; }
    }
    private EvaluatorStatusProto _evaluator_status;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"evaluator_status", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public EvaluatorStatusProto evaluator_status
    {
      get { return _evaluator_status; }
      set { _evaluator_status = value; }
    }
    private readonly global::System.Collections.Generic.List<ContextStatusProto> _context_status = new global::System.Collections.Generic.List<ContextStatusProto>();
    [global::ProtoBuf.ProtoMember(3, Name=@"context_status", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ContextStatusProto> context_status
    {
      get { return _context_status; }
    }
  
    private TaskStatusProto _task_status = null;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"task_status", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public TaskStatusProto task_status
    {
      get { return _task_status; }
      set { _task_status = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }

    private bool _recovery;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name = @"recovery", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool recovery
    {
        get { return _recovery; }
        set { _recovery = value; }
    }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"EvaluatorControlProto")]
  public partial class EvaluatorControlProto : global::ProtoBuf.IExtensible
  {
    public EvaluatorControlProto() {}
    
    private long _timestamp;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"timestamp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long timestamp
    {
      get { return _timestamp; }
      set { _timestamp = value; }
    }
    private string _identifier;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"identifier", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string identifier
    {
      get { return _identifier; }
      set { _identifier = value; }
    }
    private ContextControlProto _context_control = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"context_control", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ContextControlProto context_control
    {
      get { return _context_control; }
      set { _context_control = value; }
    }
    private KillEvaluatorProto _kill_evaluator = null;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"kill_evaluator", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public KillEvaluatorProto kill_evaluator
    {
      get { return _kill_evaluator; }
      set { _kill_evaluator = value; }
    }
    private StopEvaluatorProto _stop_evaluator = null;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name = @"stop_evaluator", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public StopEvaluatorProto stop_evaluator
    {
        get { return _stop_evaluator; }
        set { _stop_evaluator = value; }
    }
    private DoneEvaluatorProto _done_evaluator = null;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name = @"done_evaluator", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public DoneEvaluatorProto done_evaluator
    {
        get { return _done_evaluator; }
        set { _done_evaluator = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}