// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

using System.Collections.Generic;
using System.Runtime.Serialization;

using Org.Apache.REEF.Client.Avro.Local;
using Org.Apache.REEF.Client.Avro.YARN;
using Org.Apache.REEF.Utilities.Attributes;

// Mostly <auto-generated />
namespace Org.Apache.REEF.Client.Avro.Multi
{
    /// <summary>
    /// Used to serialize and deserialize Avro record org.apache.reef.reef.bridge.client.avro.AvroMultiRuntimeAppSubmissionParameters.
    /// </summary>
    [Private]
    [DataContract(Namespace = "org.apache.reef.reef.bridge.client.avro")]
    public partial class AvroMultiRuntimeAppSubmissionParameters
    {
        private const string JsonSchema = @"{""type"":""record"",""name"":""org.apache.reef.reef.bridge.client.avro.AvroMultiRuntimeAppSubmissionParameters"",""doc"":""General cross-language application submission parameters to the YARN runtime"",""fields"":[{""name"":""sharedAppSubmissionParameters"",""type"":{""type"":""record"",""name"":""org.apache.reef.reef.bridge.client.avro.AvroAppSubmissionParameters"",""doc"":""General cross-language application submission parameters shared by all runtimes"",""fields"":[{""name"":""tcpBeginPort"",""type"":""int""},{""name"":""tcpRangeCount"",""type"":""int""},{""name"":""tcpTryCount"",""type"":""int""}]}},{""name"":""localRuntimeAppParameters"",""type"":{""type"":""record"",""name"":""org.apache.reef.reef.bridge.client.avro.AvroLocalAppSubmissionParameters"",""doc"":""Cross-language application submission parameters to the Local runtime"",""fields"":[{""name"":""sharedAppSubmissionParameters"",""type"":""org.apache.reef.reef.bridge.client.avro.AvroAppSubmissionParameters""},{""name"":""maxNumberOfConcurrentEvaluators"",""type"":""int""}]}},{""name"":""yarnRuntimeAppParameters"",""type"":{""type"":""record"",""name"":""org.apache.reef.reef.bridge.client.avro.AvroYarnAppSubmissionParameters"",""doc"":""General cross-language application submission parameters to the YARN runtime"",""fields"":[{""name"":""sharedAppSubmissionParameters"",""type"":""org.apache.reef.reef.bridge.client.avro.AvroAppSubmissionParameters""},{""name"":""driverRecoveryTimeout"",""type"":""int""}]}},{""name"":""defaultRuntimeName"",""doc"":""The name of the default runtime"",""type"":""string""},{""name"":""runtimes"",""doc"":""defined runtimes"",""type"":{""type"":""array"",""items"":""string""}}]}";

        /// <summary>
        /// Gets the schema.
        /// </summary>
        public static string Schema
        {
            get
            {
                return JsonSchema;
            }
        }
      
        /// <summary>
        /// Gets or sets the sharedAppSubmissionParameters field.
        /// </summary>
        [DataMember]
        public AvroAppSubmissionParameters sharedAppSubmissionParameters { get; set; }
              
        /// <summary>
        /// Gets or sets the localRuntimeAppParameters field.
        /// </summary>
        [DataMember]
        public AvroLocalAppSubmissionParameters localRuntimeAppParameters { get; set; }
              
        /// <summary>
        /// Gets or sets the yarnRuntimeAppParameters field.
        /// </summary>
        [DataMember]
        public AvroYarnAppSubmissionParameters yarnRuntimeAppParameters { get; set; }
              
        /// <summary>
        /// Gets or sets the defaultRuntimeName field.
        /// </summary>
        [DataMember]
        public string defaultRuntimeName { get; set; }
              
        /// <summary>
        /// Gets or sets the runtimes field.
        /// </summary>
        [DataMember]
        public IList<string> runtimes { get; set; }
                
        /// <summary>
        /// Initializes a new instance of the <see cref="AvroMultiRuntimeAppSubmissionParameters"/> class.
        /// </summary>
        public AvroMultiRuntimeAppSubmissionParameters()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="AvroMultiRuntimeAppSubmissionParameters"/> class.
        /// </summary>
        /// <param name="sharedAppSubmissionParameters">The sharedAppSubmissionParameters.</param>
        /// <param name="localRuntimeAppParameters">The localRuntimeAppParameters.</param>
        /// <param name="yarnRuntimeAppParameters">The yarnRuntimeAppParameters.</param>
        /// <param name="defaultRuntimeName">The defaultRuntimeName.</param>
        /// <param name="runtimes">The runtimes.</param>
        public AvroMultiRuntimeAppSubmissionParameters(AvroAppSubmissionParameters sharedAppSubmissionParameters, AvroLocalAppSubmissionParameters localRuntimeAppParameters, AvroYarnAppSubmissionParameters yarnRuntimeAppParameters, string defaultRuntimeName, List<string> runtimes)
        {
            this.sharedAppSubmissionParameters = sharedAppSubmissionParameters;
            this.localRuntimeAppParameters = localRuntimeAppParameters;
            this.yarnRuntimeAppParameters = yarnRuntimeAppParameters;
            this.defaultRuntimeName = defaultRuntimeName;
            this.runtimes = runtimes;
        }
    }
}
