// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: class_hierarchy.proto
namespace Org.Apache.REEF.Tang.Protobuf
{
    [global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"Node")]
    public partial class Node : global::ProtoBuf.IExtensible
    {
        public Node() { }

        private string _name;
        [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name = @"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
        public string name
        {
            get { return _name; }
            set { _name = value; }
        }
        private string _full_name;
        [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name = @"full_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
        public string full_name
        {
            get { return _full_name; }
            set { _full_name = value; }
        }
        private ClassNode _class_node = null;
        [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name = @"class_node", DataFormat = global::ProtoBuf.DataFormat.Default)]
        [global::System.ComponentModel.DefaultValue(null)]
        public ClassNode class_node
        {
            get { return _class_node; }
            set { _class_node = value; }
        }
        private NamedParameterNode _named_parameter_node = null;
        [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name = @"named_parameter_node", DataFormat = global::ProtoBuf.DataFormat.Default)]
        [global::System.ComponentModel.DefaultValue(null)]
        public NamedParameterNode named_parameter_node
        {
            get { return _named_parameter_node; }
            set { _named_parameter_node = value; }
        }
        private PackageNode _package_node = null;
        [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name = @"package_node", DataFormat = global::ProtoBuf.DataFormat.Default)]
        [global::System.ComponentModel.DefaultValue(null)]
        public PackageNode package_node
        {
            get { return _package_node; }
            set { _package_node = value; }
        }
        private readonly global::System.Collections.Generic.List<Node> _children = new global::System.Collections.Generic.List<Node>();
        [global::ProtoBuf.ProtoMember(6, Name = @"children", DataFormat = global::ProtoBuf.DataFormat.Default)]
        public global::System.Collections.Generic.List<Node> children
        {
            get { return _children; }
        }

        private global::ProtoBuf.IExtension extensionObject;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
    }

    [global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"ClassNode")]
    public partial class ClassNode : global::ProtoBuf.IExtensible
    {
        public ClassNode() { }

        private bool _is_injection_candidate;
        [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name = @"is_injection_candidate", DataFormat = global::ProtoBuf.DataFormat.Default)]
        public bool is_injection_candidate
        {
            get { return _is_injection_candidate; }
            set { _is_injection_candidate = value; }
        }
        private bool _is_external_constructor;
        [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name = @"is_external_constructor", DataFormat = global::ProtoBuf.DataFormat.Default)]
        public bool is_external_constructor
        {
            get { return _is_external_constructor; }
            set { _is_external_constructor = value; }
        }
        private bool _is_unit;
        [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name = @"is_unit", DataFormat = global::ProtoBuf.DataFormat.Default)]
        public bool is_unit
        {
            get { return _is_unit; }
            set { _is_unit = value; }
        }
        private readonly global::System.Collections.Generic.List<ConstructorDef> _InjectableConstructors = new global::System.Collections.Generic.List<ConstructorDef>();
        [global::ProtoBuf.ProtoMember(4, Name = @"InjectableConstructors", DataFormat = global::ProtoBuf.DataFormat.Default)]
        public global::System.Collections.Generic.List<ConstructorDef> InjectableConstructors
        {
            get { return _InjectableConstructors; }
        }

        private readonly global::System.Collections.Generic.List<ConstructorDef> _OtherConstructors = new global::System.Collections.Generic.List<ConstructorDef>();
        [global::ProtoBuf.ProtoMember(5, Name = @"OtherConstructors", DataFormat = global::ProtoBuf.DataFormat.Default)]
        public global::System.Collections.Generic.List<ConstructorDef> OtherConstructors
        {
            get { return _OtherConstructors; }
        }

        private readonly global::System.Collections.Generic.List<string> _impl_full_names = new global::System.Collections.Generic.List<string>();
        [global::ProtoBuf.ProtoMember(6, Name = @"impl_full_names", DataFormat = global::ProtoBuf.DataFormat.Default)]
        public global::System.Collections.Generic.List<string> impl_full_names
        {
            get { return _impl_full_names; }
        }

        private string _default_implementation = "";
        [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name = @"default_implementation", DataFormat = global::ProtoBuf.DataFormat.Default)]
        [global::System.ComponentModel.DefaultValue("")]
        public string default_implementation
        {
            get { return _default_implementation; }
            set { _default_implementation = value; }
        }
        private global::ProtoBuf.IExtension extensionObject;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
    }

    [global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"NamedParameterNode")]
    public partial class NamedParameterNode : global::ProtoBuf.IExtensible
    {
        public NamedParameterNode() { }

        private string _simple_arg_class_name;
        [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name = @"simple_arg_class_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
        public string simple_arg_class_name
        {
            get { return _simple_arg_class_name; }
            set { _simple_arg_class_name = value; }
        }
        private string _full_arg_class_name;
        [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name = @"full_arg_class_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
        public string full_arg_class_name
        {
            get { return _full_arg_class_name; }
            set { _full_arg_class_name = value; }
        }
        private bool _is_set;
        [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name = @"is_set", DataFormat = global::ProtoBuf.DataFormat.Default)]
        public bool is_set
        {
            get { return _is_set; }
            set { _is_set = value; }
        }
        private bool _is_list;
        [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name = @"is_list", DataFormat = global::ProtoBuf.DataFormat.Default)]
        public bool is_list
        {
            get { return _is_list; }
            set { _is_list = value; }
        }
        private string _documentation = "";
        [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name = @"documentation", DataFormat = global::ProtoBuf.DataFormat.Default)]
        [global::System.ComponentModel.DefaultValue("")]
        public string documentation
        {
            get { return _documentation; }
            set { _documentation = value; }
        }
        private string _short_name = "";
        [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name = @"short_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
        [global::System.ComponentModel.DefaultValue("")]
        public string short_name
        {
            get { return _short_name; }
            set { _short_name = value; }
        }
        private readonly global::System.Collections.Generic.List<string> _instance_default = new global::System.Collections.Generic.List<string>();
        [global::ProtoBuf.ProtoMember(7, Name = @"instance_default", DataFormat = global::ProtoBuf.DataFormat.Default)]
        public global::System.Collections.Generic.List<string> instance_default
        {
            get { return _instance_default; }
        }

        private string _alias_name = "";
        [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name = @"alias_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
        [global::System.ComponentModel.DefaultValue("")]
        public string alias_name
        {
            get { return _alias_name; }
            set { _alias_name = value; }
        }
        private string _alias_language = "";
        [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name = @"alias_language", DataFormat = global::ProtoBuf.DataFormat.Default)]
        [global::System.ComponentModel.DefaultValue("")]
        public string alias_language
        {
            get { return _alias_language; }
            set { _alias_language = value; }
        }
        private global::ProtoBuf.IExtension extensionObject;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
    }

    [global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"PackageNode")]
    public partial class PackageNode : global::ProtoBuf.IExtensible
    {
        public PackageNode() { }

        private global::ProtoBuf.IExtension extensionObject;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
    }

    [global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"ConstructorDef")]
    public partial class ConstructorDef : global::ProtoBuf.IExtensible
    {
        public ConstructorDef() { }

        private string _full_class_name;
        [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name = @"full_class_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
        public string full_class_name
        {
            get { return _full_class_name; }
            set { _full_class_name = value; }
        }
        private readonly global::System.Collections.Generic.List<ConstructorArg> _args = new global::System.Collections.Generic.List<ConstructorArg>();
        [global::ProtoBuf.ProtoMember(2, Name = @"args", DataFormat = global::ProtoBuf.DataFormat.Default)]
        public global::System.Collections.Generic.List<ConstructorArg> args
        {
            get { return _args; }
        }

        private global::ProtoBuf.IExtension extensionObject;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
    }

    [global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"ConstructorArg")]
    public partial class ConstructorArg : global::ProtoBuf.IExtensible
    {
        public ConstructorArg() { }

        private string _full_arg_class_name;
        [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name = @"full_arg_class_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
        public string full_arg_class_name
        {
            get { return _full_arg_class_name; }
            set { _full_arg_class_name = value; }
        }
        private string _named_parameter_name = "";
        [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name = @"named_parameter_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
        [global::System.ComponentModel.DefaultValue("")]
        public string named_parameter_name
        {
            get { return _named_parameter_name; }
            set { _named_parameter_name = value; }
        }
        private bool _is_injection_future;
        [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name = @"is_injection_future", DataFormat = global::ProtoBuf.DataFormat.Default)]
        public bool is_injection_future
        {
            get { return _is_injection_future; }
            set { _is_injection_future = value; }
        }
        private global::ProtoBuf.IExtension extensionObject;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
    }
}