//<auto-generated />

using System.Collections.Generic;
using System.Runtime.Serialization;
using Org.Apache.REEF.Utilities.Attributes;

namespace Org.Apache.REEF.Common.Avro
{
    /// <summary>
    /// Used to serialize and deserialize Avro record org.apache.reef.webserver.AvroDriverInfo.
    /// </summary>
    [Private]
    [DataContract(Namespace = "org.apache.reef.webserver")]
    [KnownType(typeof(List<Org.Apache.REEF.Common.Avro.AvroReefServiceInfo>))]
    public class AvroDriverInfo
    {
        private const string JsonSchema = @"{""type"":""record"",""name"":""org.apache.reef.webserver.AvroDriverInfo"",""fields"":[{""name"":""remoteId"",""type"":""string""},{""name"":""startTime"",""type"":""string""},{""name"":""services"",""type"":{""type"":""array"",""items"":{""type"":""record"",""name"":""org.apache.reef.webserver.AvroReefServiceInfo"",""fields"":[{""name"":""serviceName"",""type"":""string""},{""name"":""serviceInfo"",""type"":""string""}]}}}]}";

        /// <summary>
        /// Gets the schema.
        /// </summary>
        public static string Schema
        {
            get
            {
                return JsonSchema;
            }
        }
      
        /// <summary>
        /// Gets or sets the remoteId field.
        /// </summary>
        [DataMember]
        public string remoteId { get; set; }
              
        /// <summary>
        /// Gets or sets the startTime field.
        /// </summary>
        [DataMember]
        public string startTime { get; set; }
              
        /// <summary>
        /// Gets or sets the services field.
        /// </summary>
        [DataMember]
        public IList<Org.Apache.REEF.Common.Avro.AvroReefServiceInfo> services { get; set; }
                
        /// <summary>
        /// Initializes a new instance of the <see cref="AvroDriverInfo"/> class.
        /// </summary>
        public AvroDriverInfo()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="AvroDriverInfo"/> class.
        /// </summary>
        /// <param name="remoteId">The remoteId.</param>
        /// <param name="startTime">The startTime.</param>
        /// <param name="services">The services.</param>
        public AvroDriverInfo(string remoteId, string startTime, IList<Org.Apache.REEF.Common.Avro.AvroReefServiceInfo> services)
        {
            this.remoteId = remoteId;
            this.startTime = startTime;
            this.services = services;
        }
    }
}