// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.
//<auto-generated />
namespace org.apache.reef.bridge.message
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;
    using Microsoft.Hadoop.Avro;

    /// <summary>
    /// Used to serialize and deserialize Avro record org.apache.reef.bridge.message.BridgeInterop.
    /// </summary>
    [DataContract(Namespace = "org.apache.reef.bridge.message")]
    public partial class BridgeInterop
    {
        private const string JsonSchema = @"{""type"":""record"",""name"":""org.apache.reef.bridge.message.BridgeInterop"",""doc"":""The BridgeInterop message is the container for all Java/CLR interop messages."",""fields"":[{""name"":""messageType"",""doc"":""The type of the bridge Java/CLR interop message contained in the wrapper message."",""type"":{""type"":""enum"",""name"":""org.apache.reef.bridge.message.MessageType"",""symbols"":[""SetupBridge"",""SystemOnStart""]}},{""name"":""setupBridge"",""type"":{""type"":""record"",""name"":""org.apache.reef.bridge.message.SetupBridge"",""fields"":[{""name"":""label"",""type"":""string""}]}},{""name"":""systemOnStart"",""type"":{""type"":""record"",""name"":""org.apache.reef.bridge.message.SystemOnStart"",""fields"":[{""name"":""dateTime"",""doc"":""Date time in seconds as a long since January 1, 1970"",""type"":""long""}]}}]}";

        /// <summary>
        /// Gets the schema.
        /// </summary>
        public static string Schema
        {
            get
            {
                return JsonSchema;
            }
        }
      
        /// <summary>
        /// Gets or sets the messageType field.
        /// </summary>
        [DataMember]
        public org.apache.reef.bridge.message.MessageType messageType { get; set; }
              
        /// <summary>
        /// Gets or sets the setupBridge field.
        /// </summary>
        [DataMember]
        public org.apache.reef.bridge.message.SetupBridge setupBridge { get; set; }
              
        /// <summary>
        /// Gets or sets the systemOnStart field.
        /// </summary>
        [DataMember]
        public org.apache.reef.bridge.message.SystemOnStart systemOnStart { get; set; }
                
        /// <summary>
        /// Initializes a new instance of the <see cref="BridgeInterop"/> class.
        /// </summary>
        public BridgeInterop()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="BridgeInterop"/> class.
        /// </summary>
        /// <param name="messageType">The messageType.</param>
        /// <param name="setupBridge">The setupBridge.</param>
        /// <param name="systemOnStart">The systemOnStart.</param>
        public BridgeInterop(org.apache.reef.bridge.message.MessageType messageType, org.apache.reef.bridge.message.SetupBridge setupBridge, org.apache.reef.bridge.message.SystemOnStart systemOnStart)
        {
            this.messageType = messageType;
            this.setupBridge = setupBridge;
            this.systemOnStart = systemOnStart;
        }
    }
}
