// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.
//<auto-generated />
namespace org.apache.reef.bridge.message
{
    using System.Runtime.Serialization;

    /// <summary>
    /// Used to serialize and deserialize Avro enum org.apache.reef.bridge.message.MessageType.
    /// </summary>
    [DataContract(Namespace = "org.apache.reef.bridge.message")]
    public enum MessageType
    {
        /// <summary>
        /// The SetupBridge symbol.
        /// </summary>
        [EnumMember]
        SetupBridge,

        /// <summary>
        /// The SystemOnStart symbol.
        /// </summary>
        [EnumMember]
        SystemOnStart,

        /// <summary>
        /// The Acknowledgement symbol.
        /// </summary>
        [EnumMember]
        Acknowledgement,

    }
}