// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.
//<auto-generated />
namespace org.apache.reef.bridge.message
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;
    using Microsoft.Hadoop.Avro;

    /// <summary>
    /// Used to serialize and deserialize Avro record org.apache.reef.bridge.message.SystemOnStart.
    /// </summary>
    [DataContract(Namespace = "org.apache.reef.bridge.message")]
    public partial class SystemOnStart
    {
        private const string JsonSchema = @"{""type"":""record"",""name"":""org.apache.reef.bridge.message.SystemOnStart"",""doc"":""Notify the C# bridge the system is now running."",""fields"":[{""name"":""dateTime"",""doc"":""Date time in seconds as a long since January 1, 1970"",""type"":""long""}]}";

        /// <summary>
        /// Gets the schema.
        /// </summary>
        public static string Schema
        {
            get
            {
                return JsonSchema;
            }
        }
      
        /// <summary>
        /// Gets or sets the dateTime field.
        /// </summary>
        [DataMember]
        public long dateTime { get; set; }
                
        /// <summary>
        /// Initializes a new instance of the <see cref="SystemOnStart"/> class.
        /// </summary>
        public SystemOnStart()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="SystemOnStart"/> class.
        /// </summary>
        /// <param name="dateTime">The dateTime.</param>
        public SystemOnStart(long dateTime)
        {
            this.dateTime = dateTime;
        }
    }
}
