// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
// 
//   http://www.apache.org/licenses/LICENSE-2.0
// 
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

namespace Org.Apache.REEF.Demo.Task
{
    /// <summary>
    /// Representation of a partition-wise operation.
    /// </summary>
    /// <typeparam name="TInput">Partition type of the input partition</typeparam>
    /// <typeparam name="TOutput">Partition type of the output partition</typeparam>
    public interface ITransform<in TInput, out TOutput>
    {
        /// <summary>
        /// Apply this transform the given input partition.
        /// </summary>
        /// <param name="input">Partition type of the input partition</param>
        /// <returns>Output object generated by applying this transform to the input</returns>
        TOutput Apply(TInput input);
    }
}
